### ISSUE TITLE
RFC - 'ember build' when doing a 'ember fxos:validate'

### ISSUE THREAD

**Issue by lholmquist** [mozilla/ember-cli-fxos#16]
Should the `ember fxos:validate` command also do an `ember build`?

I was just recently playing with this addon.  I ran `ember fxos:validate` on a project i had yet to run `ember build` on. This results in an error telling me to run ember build. 

Thats fine, but the real issue that arose for me was after i ran the build,  and ran the validate again,  i got another error about a mandatory field missing.  So i added that missing field to my `package.json`  then re-ran the validate command.  Which resulted in the same error.

I then realized i had to run ember build again.  

I think running ember build with ember fxos:validate could save a step.

Not sure if there is some other reason for not doing this?

**Comment by brittanystoroz** [comment]
Yep - you're right. I actually ran into this issue a couple of weeks ago and forgot to file an issue for it. Thanks!

**Comment by lholmquist** [comment]
No Problemo

**Comment by brittanystoroz** [comment]
Resolved as of e43e378661ff79702f75f96395ee092b434e6e81
